//
//  LocalFile.swift
//  tl2swift
//
//  Created by Code Generator
//

import Foundation

/// Represents a local file
internal struct LocalFile: Codable {
    /// True, if the file can be deleted
    internal let canBeDeleted: Bool

    /// True, if it is possible to try to download or generate the file
    internal let canBeDownloaded: Bool

    /// Download will be started from this offset. downloaded_prefix_size is calculated from this offset
    internal let downloadOffset: Int

    /// If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix
    internal let downloadedPrefixSize: Int

    /// Total downloaded file bytes. Should be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
    internal let downloadedSize: Int

    /// True, if the file is currently being downloaded (or a local copy is being generated by some other means)
    internal let isDownloadingActive: Bool

    /// True, if the local copy is fully available
    internal let isDownloadingCompleted: Bool

    /// Local path to the locally available file part; may be empty
    internal let path: String

    internal init(
        canBeDeleted: Bool,
        canBeDownloaded: Bool,
        downloadOffset: Int,
        downloadedPrefixSize: Int,
        downloadedSize: Int,
        isDownloadingActive: Bool,
        isDownloadingCompleted: Bool,
        path: String
    ) {
        self.canBeDeleted = canBeDeleted
        self.canBeDownloaded = canBeDownloaded
        self.downloadOffset = downloadOffset
        self.downloadedPrefixSize = downloadedPrefixSize
        self.downloadedSize = downloadedSize
        self.isDownloadingActive = isDownloadingActive
        self.isDownloadingCompleted = isDownloadingCompleted
        self.path = path
    }
}
